language: python

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-ci.txt"

script:
  # ignore output from install
  - snekchek

cache:
  - pip

notifications:
  email: false